import type { BasketType } from '@/lib/baskets';

/**
 * What the dish *is*, by its dominant component. Deliberately says nothing about
 * how it's cooked — that's `CookingMethod`. Together the two pick the SVG scene.
 *
 * Two values were retired once the axes were split:
 *  - `baked` described a technique, not a dish — the very confusion that made the
 *    icons wrong. Its dishes are now `veggie` plus the matching method.
 *  - `salad` was `veggie` + `raw` spelled as its own category: a salad is raw
 *    vegetables (sometimes with cheese), which is exactly what that pair means.
 *    Keeping both made `salad:pan` and `veggie:pan` two names for one picture.
 */
export type RecipeCategory = 'meat' | 'pasta' | 'soup' | 'veggie' | 'dessert';

/**
 * Which vessel the dish is cooked in. Split out of `RecipeCategory` because the
 * two were conflated: a roast chicken is `meat` yet was drawn in a frying pan.
 *
 * When a dish uses more than one vessel (pasta boiled, sauce fried; meat seared
 * then roasted), the method is the vessel where the dish reaches its *final*
 * state — seared-then-roasted pork is `oven`, not `pan`.
 *
 * No `grill` or `microwave` on purpose: a grill isn't in every kitchen, and we
 * don't want recipes that cook in a microwave.
 */
export type CookingMethod = 'pan' | 'oven' | 'pot' | 'raw';

/** How demanding a recipe is to cook. */
export type RecipeDifficulty = 'easy' | 'medium';

/** Where an ingredient comes from, relative to the current discounts. */
export type IngredientSource = 'sale' | 'pantry' | 'buy';

/** A single ingredient line within a recipe. */
export type RecipeIngredient = {
  /** Display name, e.g. "Mleté hovädzie mäso" */
  name: string;
  /** Human-readable amount, e.g. "200 g", "2 ks", "1 PL" */
  amount: string;
  source: IngredientSource;
  /** Present only for `sale` items — links to the product in the live Lidl list */
  productId?: string;
  /** Present only for `sale` items — money saved on this ingredient (€), computed in code */
  savings?: number;
};

/** A recipe generated by AI from discounted products. */
export type Recipe = {
  id: string;
  basket: BasketType;
  basketLabel: string;
  title: string;
  description: string;
  category: RecipeCategory;
  /**
   * Optional only for backward compatibility: recipes generated before this field
   * existed don't have it, and we don't rewrite `data/recipe.json`. Rendering falls
   * back to the category's default method. The generator's schema requires it.
   */
  cookingMethod?: CookingMethod;
  servings: number;
  /** Total time from start to serving, including oven preheating */
  estimatedTime: string;
  /** Hands-on time only — excludes passive waiting (oven, simmering) */
  activeTime: string;
  difficulty: RecipeDifficulty;
  ingredients: RecipeIngredient[];
  steps: string[];
  /** Approximate cost of the discounted ingredients used (€), computed in code */
  approxCost: number;
  /**
   * What the shopping actually costs (€): whole packs, since a pack can't be
   * bought in halves. Always ≥ `approxCost`, which counts only the portion the
   * dish consumes. Products sold by weight ("cena za 1 kg") contribute the same
   * to both — you buy the weight you need.
   *
   * Optional for backward compatibility: recipes generated before this existed
   * fall back to `approxCost`, same policy as `cookingMethod`.
   */
  checkoutCost?: number;
  /** Total money saved vs. regular prices (€), computed in code */
  totalSavings: number;
  /**
   * Other recipes this week that share a discounted product — i.e. that help
   * finish a pack this one only partly uses. Computed after generation.
   */
  relatedRecipeIds?: string[];
  // TODO v2 (personalization): tags?: string[];
};

/** Structure of the data/recipe.json file */
export type RecipeData = {
  generatedAt: string;
  recipes: Recipe[];
};
