/** Recipe generated by AI */
export interface Recipe {
  title: string;
  ingredients: string[];
  ingredientsFromSale: string[];
  steps: string[];
  estimatedTime: string;
  totalSavings?: string;
}

/** Structure of the data/recipe.json file */
export interface RecipeData {
  generatedAt: string;
  recipes: Recipe[];
}

