import type { BasketType } from '@/lib/baskets';

/** Dish category — drives the pre-made animated SVG icon shown for a recipe. */
export type RecipeCategory = 'meat' | 'pasta' | 'soup' | 'salad' | 'baked' | 'dessert';

/** How demanding a recipe is to cook. */
export type RecipeDifficulty = 'easy' | 'medium';

/** Where an ingredient comes from, relative to the current discounts. */
export type IngredientSource = 'sale' | 'pantry' | 'buy';

/** A single ingredient line within a recipe. */
export type RecipeIngredient = {
  /** Display name, e.g. "Mleté hovädzie mäso" */
  name: string;
  /** Human-readable amount, e.g. "200 g", "2 ks", "1 PL" */
  amount: string;
  source: IngredientSource;
  /** Present only for `sale` items — links to the product in the live Lidl list */
  productId?: string;
  /** Present only for `sale` items — money saved on this ingredient (€), computed in code */
  savings?: number;
};

/** A recipe generated by AI from discounted products. */
export type Recipe = {
  id: string;
  basket: BasketType;
  basketLabel: string;
  title: string;
  description: string;
  category: RecipeCategory;
  servings: number;
  estimatedTime: string;
  difficulty: RecipeDifficulty;
  ingredients: RecipeIngredient[];
  steps: string[];
  /** Approximate cost of the discounted ingredients used (€), computed in code */
  approxCost: number;
  /** Total money saved vs. regular prices (€), computed in code */
  totalSavings: number;
  // TODO v2 (personalization): tags?: string[];
};

/** Structure of the data/recipe.json file */
export type RecipeData = {
  generatedAt: string;
  recipes: Recipe[];
};
